#!/bin/bash

echo "Baseline"
echo "  Compile"
g++ -std=c++14 baseline.cpp -o baseline -w
if [[ $? == 0  && $# -eq 1 ]]; then
    echo "  Run"
    ./baseline data_${1}.txt out_${1}_baseline.txt
    echo " "
fi

echo "Katie"
echo "  Compile"
g++ -std=c++14 katie.cpp -o katie -Wall -Wextra -Wshadow
if [[ $? == 0  && $# -eq 1 ]]; then
    echo "  Run"
    ./katie data_${1}.txt out_${1}_katie.txt > shh.txt
    echo " "
fi

echo "Compute"
echo "  Compile"
g++ -std=c++14 compute_stats.cpp -o compute_stats -Werror
if [[ $? == 0 && $# -eq 1 ]]; then
    echo "  Run"
    echo "    Baseline"
    ./compute_stats data_${1}.txt out_${1}_baseline.txt
    echo "    Katie"
    ./compute_stats data_${1}.txt out_${1}_katie.txt
    echo " "
fi
